'use client'

import { createContext, useContext, useEffect, useState } from 'react'

type Language = 'en' | 'zh'

const LanguageContext = createContext<{
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
})

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.archive': 'Archive',
    'nav.tags': 'Tags',
    'nav.friends': 'Friends',
    'nav.cosmos': 'Cosmos',
    'nav.about': 'About',
    'cosmos.kicker': 'Voxel Planet Scene',
    'cosmos.title': 'A live planet study in voxels and light',
    'cosmos.subtitle': 'A growing collection of voxel planets rendered in real time. Drag to rotate them, and move close to disturb the surface field.',
    'cosmos.stat.planets': 'Worlds',
    'cosmos.stat.voxels': 'Voxel Instances',
    'cosmos.stat.realtime': 'Realtime Render',
    'cosmos.explode': 'Open Core',
    'cosmos.charging': 'Charging...',
    'cosmos.restore': 'Restore Shell',
    'cosmos.hint': 'Drag a planet to rotate it and move closer to stir the voxel field',
    'cosmos.planet.sun': 'Sun',
    'cosmos.planet.mercury': 'Mercury',
    'cosmos.planet.venus': 'Venus',
    'cosmos.planet.earth': 'Earth',
    'cosmos.planet.mars': 'Mars',
    'cosmos.planet.jupiter': 'Jupiter',
    'cosmos.planet.saturn': 'Saturn',
    'cosmos.planet.uranus': 'Uranus',
    'cosmos.planet.neptune': 'Neptune',
    'cosmos.credit': 'Inspired by',
    'mimo.page.kicker': '',
    'mimo.page.title': 'Notes',
    'mimo.page.subtitle': '',
    'mimo.front.title': 'HELLO, I\'M HAIBARA',
    'mimo.front.altTitle': '你好，我是 Haibara',
    'mimo.front.label': 'ABOUT ME',
    'mimo.back.title': '',
    'mimo.back.p1': '',
    'mimo.back.p2': '',
    'mimo.back.pullText': 'A millennium past, I beheld a Nascent Soul cultivator\'s personal realm and was filled with envy. I vowed to grow stronger, forsaking worldly attachments to embark upon the path of immortal cultivation. Though but a rogue cultivator, I persevered through countless tribulations—a century refining Qi, four centuries establishing Foundation, a millennium forming the Golden Core, two millennia breaking through to Nascent Soul. After another millennium, I encountered a bottleneck and entered death seclusion. Today, four thousand years hence, I have finally achieved Spirit Severing. Looking back upon the vicissitudes, the gulf between immortal and mortal defies words—such is the mortal realm.',
    'mimo.back.pullHint': 'DRAG THE TAIL',
    'mimo.back.toggle': 'Click Here To Flip Back',
    'home.mimo.title': 'HELLO, I\'M HAIBARA',
    'home.mimo.altTitle': '你好，我是 Haibara',
    'home.mimo.label': 'ABOUT ME',
    'home.hero.title': 'Thoughts on design,\ncode, and craft',
    'home.hero.subtitle': 'A collection of essays exploring the intersection of technology and creativity.',
    'home.recent': 'Recent Writing',
    'archive.title': 'Archive',
    'archive.subtitle': 'Browse all articles by time',
    'archive.all': 'All Years',
    'tags.title': 'Tag Cloud',
    'tags.all': 'All Tags',
    'tags.articles': 'articles',
    'pagination.prev': 'Previous',
    'pagination.next': 'Next',
    'friends.title': 'Friends',
    'friends.subtitle': 'Awesome friends',
    'friends.apply.title': 'Apply for Friend Link',
    'friends.apply.welcome': 'Welcome to exchange friend links! Please leave a message in the comments or contact me via email:',
    'friends.apply.name': 'Site Name: Haerin Blog',
    'friends.apply.siteName': 'Site Name',
    'friends.apply.url': 'Site URL: https://haibara406.github.io/Haerin-Blog/',
    'friends.apply.siteUrl': 'Site URL',
    'friends.apply.desc': 'Site Description: Recording technology and life',
    'friends.apply.siteDesc': 'Site Description',
    'friends.apply.siteDescValue': 'Recording technology and life',
    'friends.apply.avatar': 'Avatar: /avatar.png',
    'friends.apply.note': 'Please ensure your website content is healthy, positive, and accessible.',
    'friends.empty': 'No friend links yet, welcome to apply!',
    'about.hero.title': 'Hi, I\'m Haibara',
    'about.hero.subtitle': 'Java Developer & Tech Enthusiast',
    'about.hero.contact': 'Get in Touch',
    'about.title': 'About Me',
    'about.intro.p1': 'Hello! I\'m Haibara, currently a junior student majoring in Computer Science at Chengdu University. I mainly study Java development and love creating various interesting projects.',
    'about.intro.p2': 'I enjoy vibe coding, writing small projects, and exploring new technologies. In my spare time, I like watching anime and playing League of Legends, enjoying the balance between code and life.',
    'about.intro.p3': 'This blog is where I record my technical learning and share experiences. I hope to grow together with everyone.',
    'about.stats.articles': 'Articles',
    'about.stats.words': 'Words',
    'about.stats.tags': 'Tags',
    'about.stats.categories': 'Categories',
    'about.skills.title': 'Skills',
    'about.projects.title': 'Projects',
    'about.contact.title': 'Contact',
    'about.contact.email': 'Email',
    'about.contact.location': 'Location',
    'about.contact.location.value': 'Chengdu, Sichuan, China',
    'post.back': 'Back',
    'post.toc': 'Table of Contents',
    'post.comments': 'Comments',
    'post.published': 'Published',
    'post.updated': 'Updated',
    'post.minRead': 'min read',
    'post.words': 'words',
    'post.share': 'Share',
    'search.placeholder': 'Search articles...',
    'search.empty': 'No articles found',
    'search.results': 'results',
    'search.close': 'Press ESC to close',
    'common.close': 'Close',
    'common.prev': 'Previous',
    'common.next': 'Next',
    'footer.rights': 'All rights reserved.',
  },
  zh: {
    'nav.home': '首页',
    'nav.archive': '归档',
    'nav.tags': '标签',
    'nav.friends': '友链',
    'nav.cosmos': '星球',
    'nav.about': '关于',
    'cosmos.kicker': '体素行星场景',
    'cosmos.title': '一个可交互的体素行星实验',
    'cosmos.subtitle': '一个持续扩展的体素行星集合，全部实时 3D 渲染。拖动可以旋转，鼠标靠近时会扰动表面。',
    'cosmos.stat.planets': '星球',
    'cosmos.stat.voxels': '体素实例',
    'cosmos.stat.realtime': '实时渲染',
    'cosmos.explode': '炸开核心',
    'cosmos.charging': '蓄力中...',
    'cosmos.restore': '还原星壳',
    'cosmos.hint': '拖动行星旋转，靠近时会产生扰动',
    'cosmos.planet.sun': '太阳',
    'cosmos.planet.mercury': '水星',
    'cosmos.planet.venus': '金星',
    'cosmos.planet.earth': '地球',
    'cosmos.planet.mars': '火星',
    'cosmos.planet.jupiter': '木星',
    'cosmos.planet.saturn': '土星',
    'cosmos.planet.uranus': '天王星',
    'cosmos.planet.neptune': '海王星',
    'cosmos.credit': '灵感来自',
    'mimo.page.kicker': '',
    'mimo.page.title': '随笔',
    'mimo.page.subtitle': '',
    'mimo.front.title': '你好，我是 Haibara',
    'mimo.front.altTitle': 'HELLO, I\'M HAIBARA',
    'mimo.front.label': '关于我',
    'mimo.back.title': '',
    'mimo.back.p1': '',
    'mimo.back.p2': '',
    'mimo.back.pullText': '千年以前，看见元婴强者自己的小世界，非常羡慕，于是心中立誓，我也要变强，后抛弃世间情爱，终踏上修仙一途，虽一介散修，但亦往，经历千磨万难，炼气百年，四百年筑基，一千年结丹，两千年突破元婴，又一千年后遭遇瓶颈，决心闭门死关，四千年后的今日，终于突破化神，感叹回首沧桑，道不尽仙凡殊途，尽人间。',
    'mimo.back.pullHint': '从这里拖动',
    'mimo.back.toggle': '点击这里翻回正面',
    'home.mimo.title': '你好，我是 Haibara',
    'home.mimo.altTitle': 'HELLO, I\'M HAIBARA',
    'home.mimo.label': '关于我',
    'home.hero.title': '关于设计、\n代码与创造的思考',
    'home.hero.subtitle': '探索技术与创意交汇的文章集。',
    'home.recent': '最近文章',
    'archive.title': '归档',
    'archive.subtitle': '按时间浏览所有文章',
    'archive.all': '全部年份',
    'tags.title': '标签云',
    'tags.all': '所有标签',
    'tags.articles': '篇',
    'pagination.prev': '上一页',
    'pagination.next': '下一页',
    'friends.title': '友链',
    'friends.subtitle': '优秀的朋友们',
    'friends.apply.title': '申请友链',
    'friends.apply.welcome': '欢迎交换友链！请在评论区留言或通过邮件联系我：',
    'friends.apply.name': '网站名称：Haerin Blog',
    'friends.apply.siteName': '网站名称',
    'friends.apply.url': '网站地址：https://haibara406.github.io/Haerin-Blog/',
    'friends.apply.siteUrl': '网站地址',
    'friends.apply.desc': '网站描述：记录技术与生活',
    'friends.apply.siteDesc': '网站描述',
    'friends.apply.siteDescValue': '记录技术与生活',
    'friends.apply.avatar': '头像：/avatar.png',
    'friends.apply.note': '请确保您的网站内容健康、积极向上，并且能够正常访问。',
    'friends.empty': '暂无友链，欢迎申请交换友链！',
    'about.hero.title': '你好，我是 Haibara',
    'about.hero.subtitle': 'Java 开发者 & 技术爱好者',
    'about.hero.contact': '联系我',
    'about.title': '关于我',
    'about.intro.p1': '你好！我是 Haibara，目前是成都大学计算机相关专业的大三学生。主要学习 Java 开发，热衷于开发各种各样有趣的小玩意。',
    'about.intro.p2': '平时喜欢 vibe coding，写写小项目，探索新技术。闲暇时光喜欢看动漫、玩英雄联盟，享受代码与生活的平衡。',
    'about.intro.p3': '这个博客是我记录技术学习和分享经验的地方，希望能与大家一起成长。',
    'about.stats.articles': '文章',
    'about.stats.words': '字',
    'about.stats.tags': '标签',
    'about.stats.categories': '分类',
    'about.skills.title': '技能',
    'about.projects.title': '个人项目',
    'about.contact.title': '联系方式',
    'about.contact.email': '邮箱',
    'about.contact.location': '地点',
    'about.contact.location.value': '中国四川成都',
    'post.back': '返回',
    'post.toc': '目录',
    'post.comments': '评论',
    'post.published': '发布',
    'post.updated': '更新',
    'post.minRead': '分钟阅读',
    'post.words': '字',
    'post.share': '分享',
    'search.placeholder': '搜索文章...',
    'search.empty': '没有找到相关文章',
    'search.results': '个结果',
    'search.close': '按 ESC 关闭',
    'common.close': '关闭',
    'common.prev': '上一页',
    'common.next': '下一页',
    'footer.rights': '版权所有。',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const savedLang = (localStorage.getItem('language') as Language) || 'en'
    setLanguageState(savedLang)
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
